# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Compile Groovy code and generate sources
      run: |
        mvn gplus:compile generate-sources package
        MAINJAR=$(ls -1 *.jar  | grep -v sources\.jar) 
        echo $MAINJAR
        echo "::set-output name=MAINJAR::$MAINJAR"

    - name: Publish Package to Github Maven Repo
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

#  mvn install:install-file -DgroupId=com.eficode.atlassian -DartifactId=jirainstancemanger -Dversion=1.0-SNAPSHOT -Dfile=../jirainstancemanger-1.0-SNAPSHOT.jar  -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true -Dpackaging=jar -Dsources=../jirainstancemanger-1.0-SNAPSHOT-sources.jar