name: Updated repository in packages branch

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: "maven"

      #Manually first (once) set up an orphaned branch:
      # git switch --orphan packages
      # git commit --allow-empty -m "Initial commit on packages branch"
      # git push origin packages:packages

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Installing the different profile editions of the package
        run: |
          
          declare -a profiles=("groovy-2.5" "groovy-3.0")  #Profiles to build
          
          mkdir -p repository/com/eficode/atlassian/jirainstancemanager
          baseVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Base version is $baseVersion"
          
          for profile in "${profiles[@]}"; do
          
            echo "Compiling, Packaging and Installing $baseVersion-$profile version of library to local m2 directory"
          
            mvn versions:revert
          
            mvn versions:set -DnewVersion="$baseVersion-$profile"
          
            mvn install -P "$profile" -DcreateChecksum=true
            
          done
  

      - name: Copying JAR files
        run: |
          echo Copying the new JAR files to repository which will be added to git branch "packages"
          rsync -avh --checksum ~/.m2/repository/com/eficode/atlassian/jirainstancemanager/ repository/com/eficode/atlassian/jirainstancemanager/
      - name: Committing and pushing JAR files
        run: |
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo Adding repository dir temporarily so stash picks it up
          git add repository
          echo Stashing current changes
          git stash
          echo Running git fetch
          git fetch
          echo Checking out Packages repo
          git checkout packages
          echo Applying stash, overwriting any checked out changes
          git checkout stash -- .
          echo Running git reset, to ignore any automatically added tracked changes
          git reset
          echo Adding repository files to git
          git add repository/*
          echo Committing changes
          git commit -m "Updated packages to $VERSION"
          echo Pushing changes
          git push