name: Maven Package

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Compile Groovy code and generate sources
      run: mvn gplus:compile generate-sources package

    - name: Publish Package to Github Maven Repo
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

      #Manually first (once) set up an orphaned branch:
      # git switch --orphan packages
      # git commit --allow-empty -m "Initial commit on packages branch"
      # git push github packages:packages

    - name: Install Package to repository directory
      run: |  
        MAINJAR=$(ls -1 target/*.jar  | grep -v sources\.jar) 
        SOURCEJAR=$(ls -1 target/*.jar  | grep sources\.jar) 
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo Main JAR: $MAINJAR
        echo Source JAR: $SOURCEJAR
        echo Version: $VERSION
        mkdir -p repository
        echo Installing JAR in repository directory
        mvn install:install-file -DpomFile=pom.xml -DlocalRepositoryPath=repository/ -Dfile="$MAINJAR" -Dsources="$SOURCEJAR" -DgeneratePom=true -DcreateChecksum=true
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        echo Running git fetch
        git fetch
        echo Stashing current changes
        git stash
        echo Checking out Packages repo
        git checkout packages
        echo Applying stash
        git stash apply
        echo Adding repository files to git
        git add repository/*
        echo Committing changes
        git commit -m "Updated packages"
        echo Pushing changes
        git push
